package com.parking_reservation.entity;

public enum NotificationType {
    BOOKING_APPROVED,
    BOOKING_REJECTED,
    BOOKING_CANCELLED,
    HELMET_ISSUED,
    HELMET_REJECTED,
    HELMET_RETURNED,
    TICKET_ASSIGNED,
    TICKET_STATUS_CHANGED,
    TICKET_COMMENT_ADDED,
    BOOKING_REMINDER,
    BOOKING_ENDING_SOON,
    BOOKING_ENDED
}
